More on pipenv (#81)
add husky git hook to maintain pipenv. 
some changes in documentation and troubleshooting

diff --git a/.husky/post-merge b/.husky/post-merge
--- a/.husky/post-merge
+++ b/.husky/post-merge
@@ -5,8 +5,6 @@
 
 
 
-printf "${HUSKY} ${GREEN} Updating python environment from ${REQUIREMENTS}...\n ${NC} "
-$PIP install -r $REQUIREMENTS
 
 printf "${HUSKY} ${GREEN} Updating js environment...\n ${NC} "
 yarn install
@@ -15,4 +13,8 @@ printf "${HUSKY} ${GREEN} Updating js environment in frontend...\n ${NC} "
 cd frontend
 yarn install
 
+printf "${HUSKY} ${GREEN} Updating python environment from Pipefile...\n ${NC} "
+if ! pipenv install; then
+    printf "${HUSKY} ${RED} Failed to automatically update pipenv. please do it manually ${NC} "
+fi 
 
